image: golang:1.21-alpine

variables:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0

stages:
  - build
  - release

.build_template: &build_template
  stage: build
  script:
    - apk add --no-cache git
    - go build -ldflags="-w -s" -o vault-loader-$GOOS-$GOARCH
    - tar czf vault-loader-$GOOS-$GOARCH.tar.gz vault-loader-$GOOS-$GOARCH
  only:
    - master
  artifacts:
    paths:
      - vault-loader-$GOOS-$GOARCH.tar.gz
    expire_in: 1 week

build_linux_amd64:
  <<: *build_template
  variables:
    GOOS: linux
    GOARCH: amd64

build_linux_arm64:
  <<: *build_template
  variables:
    GOOS: linux
    GOARCH: arm64

build_darwin_amd64:
  <<: *build_template
  variables:
    GOOS: darwin
    GOARCH: amd64

build_darwin_arm64:
  <<: *build_template
  variables:
    GOOS: darwin
    GOARCH: arm64

build_windows_amd64:
  <<: *build_template
  variables:
    GOOS: windows
    GOARCH: amd64

build_windows_arm64:
  <<: *build_template
  variables:
    GOOS: windows
    GOARCH: arm64

pages:
  stage: release
  dependencies:
    - build_linux_amd64
    - build_linux_arm64
    - build_darwin_amd64
    - build_darwin_arm64
    - build_windows_amd64
    - build_windows_arm64
  script:
    - mkdir -p public
    - cp install.sh public/
    - cp vault-loader-*.tar.gz public/
  artifacts:
    paths:
      - public
    expire_in: never
  only:
    - master

dockerize:
  stage: release
  image: idotdigital/builder
  before_script:
    - echo $DOCKER_TOKEN | docker login -u luiskugel --password-stdin
    - docker buildx create --name mybuilder --use
    - tar xzf vault-loader-linux-amd64.tar.gz
    - tar xzf vault-loader-linux-arm64.tar.gz
  needs:
    - build_linux_amd64
    - build_linux_arm64
  script:
    - docker buildx build --platform linux/amd64,linux/arm64
      --tag idotdigital/vault-loader:$CI_COMMIT_REF_NAME
      --tag idotdigital/vault-loader:$CI_COMMIT_SHA
      --tag idotdigital/vault-loader:latest
      --no-cache
      --pull
      --push .
  only:
    - master
  tags:
    - amd64
