image: golang:1.21-alpine

variables:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0

stages:
  - build
  - release

.build_template: &build_template
  stage: build
  script:
    - apk add --no-cache git
    - go build -ldflags="-w -s" -o vault-loader-$GOOS-$GOARCH
    - tar czf vault-loader-$GOOS-$GOARCH.tar.gz vault-loader-$GOOS-$GOARCH
  artifacts:
    paths:
      - vault-loader-$GOOS-$GOARCH.tar.gz
    expire_in: 1 week

build_linux_amd64:
  <<: *build_template
  variables:
    GOOS: linux
    GOARCH: amd64

build_linux_arm64:
  <<: *build_template
  variables:
    GOOS: linux
    GOARCH: arm64

build_darwin_amd64:
  <<: *build_template
  variables:
    GOOS: darwin
    GOARCH: amd64

build_darwin_arm64:
  <<: *build_template
  variables:
    GOOS: darwin
    GOARCH: arm64

build_windows_amd64:
  <<: *build_template
  variables:
    GOOS: windows
    GOARCH: amd64

build_windows_arm64:
  <<: *build_template
  variables:
    GOOS: windows
    GOARCH: arm64

pages:
  stage: release
  dependencies:
    - build_linux_amd64
    - build_linux_arm64
    - build_darwin_amd64
    - build_darwin_arm64
    - build_windows_amd64
    - build_windows_arm64
  script:
    - mkdir -p public
    - |
      cat > public/index.html << 'EOF'
      <!DOCTYPE html>
      <html>
      <head>
        <title>Vault Loader Releases</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
          }
          h1 { color: #333; }
          .release {
            margin: 20px 0;
            padding: 15px;
            border: 1px solid #ddd;
            border-radius: 4px;
          }
          .release h2 { margin-top: 0; }
          .release p { margin: 5px 0; }
          .release a {
            color: #0366d6;
            text-decoration: none;
          }
          .release a:hover {
            text-decoration: underline;
          }
        </style>
      </head>
      <body>
        <h1>Vault Loader Releases</h1>
        <div class="release">
          <h2>Latest Release</h2>
          <p>Download the latest version of Vault Loader for your platform:</p>
          <ul>
            <li><a href="vault-loader-linux-amd64.tar.gz">Linux (amd64)</a></li>
            <li><a href="vault-loader-linux-arm64.tar.gz">Linux (arm64)</a></li>
            <li><a href="vault-loader-darwin-amd64.tar.gz">macOS (amd64)</a></li>
            <li><a href="vault-loader-darwin-arm64.tar.gz">macOS (arm64)</a></li>
            <li><a href="vault-loader-windows-amd64.tar.gz">Windows (amd64)</a></li>
            <li><a href="vault-loader-windows-arm64.tar.gz">Windows (arm64)</a></li>
          </ul>
        </div>
      </body>
      </html>
      EOF
    - cp vault-loader-*.tar.gz public/
  artifacts:
    paths:
      - public
    expire_in: never
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
